# Changes here will be overwritten by Copier
_commit: b18a505
_src_path: .
add_extension: jupyter
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A Jupyter-Python project template
project_name: jupyter template
python_version_primary: '3.11'
team: Python Project Template Authors
