# Changes here will be overwritten by Copier
_commit: 47f880e
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: jupyter
add_wiki: true
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A Jupyter-Python project template
project_name: python template jupyter
python_version_primary: '3.11'
team: Python Project Template Authors
